version: '3'
services:
  app:
    build: app/.
    container_name: monitoring-app
    image: monitoring:latest
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: myredispassword
      REDIS_DB: 0
    depends_on:
      - redis
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass myredispassword
    environment:
      REDIS_PASSWORD: myredispassword
    ports:
      - "6379:6379"
  client:
    build: client/.
    container_name: monitoring-client
    image: client:latest
    depends_on:
      - app
