pipeline {
   agent { label 'JenkinsAgent' }
   stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                branches: [[name: '*/main']], 
                extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/tizianoadv/monitoring_cicd.git']]
                )
            }
        }
        stage('Build') {
            steps {
                sh 'bash jenkins/build_run.sh'
            }
        }
        stage('Unit Test') {
            steps {
                sh 'bash jenkins/test.sh' 
            }
        } 
        stage('Push') {
            steps {
                sh 'bash jenkins/push.sh' 
            }
        }   
        stage('Deploy'){
            steps {
                ansiblePlaybook colorized: true, 
                credentialsId: 'sshDevServer', 
                inventory: 'ansible/inventory.yaml', 
                playbook: 'ansible/playbook.yaml'
            }
        }
        stage('JMeter Test'){
            steps {
                sh 'mkdir jmeter/performance'
                sh '/usr/bin/jmeter/apache-jmeter-5.5/bin/jmeter -n -t jmeter/FirstTestJmeter.jmx -l jmeter/performance/results.jtl'
                sh 'cat jmeter/performance/results.jtl'
                perfReport 'results.jtl'
            }
        }
    }
}